### ISSUE TITLE
Markbot Submission

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/accessibility-fixer-upper#3]
Hi @muxlowc,

I remember you mentioning in the lecture last week that some people were encountering issues with screenshots matching when they were trying to submit this assignment through Markbot and I seem to be having the same problem. The 960px screen is within the acceptable range but my 320px if 13% different when it needs to be 12%. Looking at the screenshots they are practically identical except the text in the reference photo appears to be bold. When I add a bold tag on my text, it hasn't made a difference when being compared in Markbot. I've attached some screenshots from Markbot.

<img width="501" alt="Screen Shot 2020-04-13 at 11 28 42 AM" src="https://user-images.githubusercontent.com/55094049/79133482-1761f800-7d7a-11ea-8d0f-1c8af080264a.png">
<img width="497" alt="Screen Shot 2020-04-13 at 11 28 51 AM" src="https://user-images.githubusercontent.com/55094049/79133484-17fa8e80-7d7a-11ea-9e68-24a6245dd69b.png">
<img width="318" alt="Screen Shot 2020-04-13 at 11 29 22 AM" src="https://user-images.githubusercontent.com/55094049/79133487-192bbb80-7d7a-11ea-8414-bf0cb6b8c3a9.png">
<img width="311" alt="Screen Shot 2020-04-13 at 11 29 30 AM" src="https://user-images.githubusercontent.com/55094049/79133493-1a5ce880-7d7a-11ea-8a44-ee93805e7b23.png">

**Comment by muxlowc** [comment]
@riannazandbelt  yep looks good, ill go give you the mark!
